import { test, expect } from '@playwright/test';

test('captain creates a squad, saves a full lineup, reviews attendance and exports to tactics', async ({page}) => {
  const errors=[];page.on('pageerror', e=>errors.push(e.message));
  await page.request.post('/api/login',{form:{password:'test-password'}});
  const unique=Date.now();
  const members=[];
  for(let i=0;i<10;i++) {
    const r=await page.request.post('/api/squad/players',{data:{name:`Test ${unique} ${i}`,number:i+1,position:i===0?'POR':'MC'}});
    expect(r.ok()).toBeTruthy();members.push(await r.json());
  }
  await page.goto('/gestion-plantilla');
  await page.getByRole('button',{name:'Plantilla',exact:true}).click();
  await page.getByRole('button',{name:'Añadir jugador',exact:true}).click();
  await page.getByLabel('ID / nombre en el juego').fill(`Captain ${unique}`);
  await page.getByLabel('Dorsal',{exact:true}).fill('11');
  await page.locator('#photo-upload').setInputFiles('static/assets/tactical-ball.png');
  await expect(page.locator('[name=avatarUrl]')).not.toHaveValue('');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.locator('#editor')).not.toBeVisible();
  await expect(page.locator('#player-table')).toContainText(`Captain ${unique}`);
  members.push((await (await page.request.get('/api/squad/players')).json()).find(p=>p.name===`Captain ${unique}`));
  await page.getByRole('button',{name:'Dia de partido',exact:true}).click();
  await page.locator('#day-date').fill('2031-02-12');
  await page.locator('#day-date').dispatchEvent('change');
  await expect(page.locator('#day-date')).toHaveValue('2031-02-12');
  for(let i=0;i<11;i++){
    await page.locator(`.slot[data-id="${i}"]`).click();
    await page.locator(`#pick-list [data-id="${members[i].id}"]`).click();
  }
  await expect(page.locator('.section-title').first()).toContainText('11/11');
  await page.getByRole('button',{name:'Marcar titulares presentes'}).click();
  await page.getByRole('button',{name:'Anadir partido',exact:true}).click();
  await page.getByLabel('Rival',{exact:true}).fill('Rival de prueba');
  await page.getByLabel('Competicion',{exact:true}).selectOption('PLG');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.locator('.fixture').first()).toContainText('Rival de prueba');
  await page.getByRole('button',{name:'Guardar dia',exact:true}).click();
  await expect(page.locator('#save-state')).toHaveText('Guardado');
  await page.getByRole('button',{name:'A pizarra',exact:true}).click();
  await expect(page.locator('#toast')).toContainText('Once disponible');
  const templates=await (await page.request.get('/api/tactical-lineup-templates')).json();
  expect(templates.find(t=>t.name==='KORU 2031-02-12').players).toHaveLength(11);
  await page.getByLabel(`Disponibilidad de ${members[0].name}`,{exact:true}).selectOption('unavailable');
  await expect(page.locator('.section-title').first()).toContainText('10/11');
  await page.getByRole('button',{name:'Guardar dia',exact:true}).click();
  await expect(page.locator('#save-state')).toHaveText('Guardado');
  const saved=await (await page.request.get('/api/squad/days/2031-02-12')).json();
  expect(saved.responses[members[0].id].attendance).toBe('present');
  expect(saved.lineup[0]).toBeNull();
  await page.getByRole('button',{name:'Asistencia',exact:true}).click();
  await page.locator('#month').fill('2031-02');
  await page.locator('#month').dispatchEvent('change');
  await page.getByRole('button',{name:'Mes completo',exact:true}).click();
  await expect(page.locator('.attendance-calendar')).toContainText('Lun');
  await page.getByRole('button',{name:'Pruebas',exact:true}).click();
  await page.getByRole('button',{name:'Nuevo candidato'}).click();
  await page.getByLabel('Nombre',{exact:true}).fill('Candidato e2e');
  await page.getByLabel('Estado',{exact:true}).selectOption('scheduled');
  await page.getByLabel('Fecha de prueba').fill('2031-02-15');
  await page.getByRole('button',{name:'Guardar',exact:true}).click();
  await expect(page.locator('#workspace')).toContainText('Candidato e2e');
  await page.getByRole('button',{name:'Dia de partido',exact:true}).click();
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'artifacts/squad-desktop.png',fullPage:true});
  await page.setViewportSize({width:375,height:812});
  await page.screenshot({path:'artifacts/squad-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  expect(await page.locator('.response-row .person').evaluateAll(items=>items.every(el=>el.scrollWidth<=el.clientWidth+1))).toBeTruthy();
  expect(errors).toEqual([]);
});

test('simple calendar saves every state, restores it after reload and safely removes players',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.request.post('/api/login',{form:{password:'test-password'}});
  const p=await (await page.request.post('/api/squad/players',{data:{name:'Calendario sencillo '+Date.now(),number:8,position:'MC'}})).json();
  await page.goto('/gestion-plantilla');
  await expect(page.getByRole('heading',{name:'Asistencia de la plantilla'})).toBeVisible();
  await page.locator('#month').fill('2032-06');
  await page.locator('#month').dispatchEvent('change');
  const cell=page.locator('[data-cal=record][data-date="2032-06-01"][data-id="'+p.id+'"]');
  for(const [state,label] of [['present','Está'],['absent','No está'],['bench','Está, pero no jugó'],['pending','Sin marcar']]){
    await cell.click();
    await page.getByRole('button',{name:label,exact:true}).click();
    await expect(page.locator('#editor')).not.toBeVisible();
    await expect(cell).toHaveClass(new RegExp(state));
    const row=(await (await page.request.get('/api/squad/days/2032-06-01')).json()).responses[p.id];
    expect(row.attendance).toBe({present:'present',absent:'absent',bench:'present',pending:'pending'}[state]);
  }
  await cell.click();
  await page.getByRole('button',{name:'Está, pero no jugó',exact:true}).click();
  await expect(cell).toHaveClass(/bench/);
  await page.reload();
  await page.locator('#month').fill('2032-06');
  await page.locator('#month').dispatchEvent('change');
  await expect(cell).toHaveClass(/bench/);
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Historial detallado',exact:true}).click();
  await expect(page.locator('#player-history')).toBeVisible();
  await page.getByRole('button',{name:'Mes completo',exact:true}).click();
  await page.getByRole('button',{name:'Volver al calendario sencillo',exact:false}).click();
  await expect(page.getByRole('heading',{name:'Asistencia de la plantilla'})).toBeVisible();
  await page.screenshot({path:'artifacts/calendar-simple-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/calendar-simple-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'Quitar a '+p.name+' de la plantilla',exact:true}).click();
  await expect(cell).toHaveCount(0);
  const savedPlayers=await (await page.request.get('/api/squad/players')).json();
  expect(savedPlayers.find(item=>item.id===p.id).status).toBe('inactive');
  expect((await (await page.request.get('/api/squad/days/2032-06-01')).json()).responses[p.id].participation).toBe('not_played');
  expect(errors).toEqual([]);
});
